### ISSUE TITLE
Fix Travis config to support PHP v5.3

### ISSUE THREAD

**Issue by terales** [samdark/sitemap#51]
We have [an error at Travis job](https://travis-ci.org/samdark/sitemap/jobs/306631737):
```
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
```

[Solution](https://docs.travis-ci.com/user/reference/trusty#PHP-images) is to add php 5.3 to matrix:
```
matrix:
  include:
    - php: 5.3
      dist: precise
```
